[package]
name = "strike_ln_tipping"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
types = []
errors = ["reqwest"]
tipping = ["types", "errors", "reqwest", "tokio", "serde_json"]
default = ["tipping"]

[dependencies]
reqwest = { version = "0.11", features = ["json"], optional = true }
tokio = { version = "1", features = ["full"], optional = true }
serde_json = { version = "1.0", optional = true }
serde = { version = "1.0", features = ["derive"] }


[dev-dependencies]
dotenv = "0.15.0"